### ISSUE TITLE
Interface orientation changes

### ISSUE THREAD

**Issue by mano1337o** [tungfam/ImageInNavigationBarDemo#3]
Thanks for this great piece of code.
It would be perfect with orientation support.

**Comment by tungfam** [comment]
Hello @mano1337o , thanks a lot for the suggestion!

Will implement it!

**Comment by mano1337o** [comment]
👍 Thanks to you :)

**Comment by tungfam** [comment]
@mano1337o implemented support for horizontal. check it out in the last PR:)
