### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by janczakb** [tungfam/ImageInNavigationBarDemo#5]
the scaling animation does not work. The image is still the same size

**Comment by tungfam** [comment]
@janczakb thanks for sharing the feedback. May I ask if you followed all the steps on this [tutorial](https://blog.uptech.team/how-to-build-resizing-image-in-navigation-bar-with-large-title-8ba2e8bcb840?gi=9159644494c6)?

**Comment by furiosFast** [comment]
I confirm that making it does not always work on ios 11...the problem is due to the lines of code:
`UIDevice.current.orientation.isPortrait`

**Comment by tungfam** [comment]
@furiosFast hm I see. Interesting.

I'll push a commit that may fix it. Please take a look on the updated version to see if it solves the issue.

Thank you.

**Comment by tungfam** [comment]
solved in commit: [link](https://github.com/tungfam/ImageInNavigationBarDemo/commit/7eeaa568013dfaa67d7c0b94e543f1ede42e5c88).
