### ISSUE TITLE
Just use heightAnchor will be work.  don't need observe anything and override any functions

### ISSUE THREAD

**Issue by baryon** [tungfam/ImageInNavigationBarDemo#7]
```
        let heightDiff = -(navigationBar.frame.size.height*10/100)

        NSLayoutConstraint.activate([
            imageView.rightAnchor.constraint(equalTo: navigationBar.rightAnchor,
                                             constant: -10),
            imageView.bottomAnchor.constraint(equalTo: navigationBar.bottomAnchor,
                                              constant: -Const.ImageBottomMarginForLargeState),
            imageView.heightAnchor.constraint(equalTo: navigationBar.heightAnchor, constant: heightDiff),
            imageView.widthAnchor.constraint(equalTo: imageView.heightAnchor)
            ])
```

**Comment by tungfam** [comment]
@baryon thanks a lot for the suggestion! initially, of course, I was trying to implement it with constraints. but it didn't work for me at that time.

did it work for you?

**Comment by Rushang007** [comment]
how to set image left side in navigation bar ?

**Comment by tungfam** [comment]
@Rushang007 change this line:
`imageView.rightAnchor.constraint(equalTo: navigationBar.rightAnchor, constant: -Const.ImageRightMargin)` to use the `.leftAnchor`

**Comment by Rushang007** [comment]
@tungfam thanks for replay 
Yes I already tried this but it's not perfect, see below 

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-09 at 07 24 08](https://user-images.githubusercontent.com/16713953/68520935-16f09d00-02c2-11ea-931c-fb9ee6a7ffac.png)

**Comment by tungfam** [comment]
@Rushang007 sure, it's not :) i can't make suggestions on how to do it without seeing the designs. so i answered the question how you asked it. please show the design of what you want to achieve.

**Comment by Rushang007** [comment]
Ok, like this 

![Screenshot 2019-11-09 at 2 41 03 PM](https://user-images.githubusercontent.com/16713953/68526176-2510de80-02ff-11ea-8443-729bef41e35a.png)

**Comment by tungfam** [comment]
@baryon please move the conversion to here: https://github.com/tungfam/ImageInNavigationBarDemo/issues/9

**Comment by tungfam** [comment]
Indeed it does work, but a bit differently.
For example, the bottom spacing between the image and bottom of nav bar is not changed.
But I think it's doable using constraints with a multiplier.

If I will have time I'll try to rewrite it using constraint. thanks for the suggestion @baryon.

**Comment by Rushang007** [comment]
@tungfam Thanks :)
