### ISSUE TITLE
Image view under the normal navigation bar

### ISSUE THREAD

**Issue by AndreiBoariu** [tungfam/ImageInNavigationBarDemo#8]
@tungfam Really appreciate your hard work on this post. You did a great job!

I would be very glad if you can guide me a little. I have to do the same on my app, but similar to AppStore app. 

**1.** I mean that `imageview` to go under the navigation bar!  Why? because I have to display one `right bar button item` anytime in my screen, and when scrolling up, image view goes over the bar button.
**OR 2.** at least to set imageView alpha to 0 while scrolling up. 
**OR 3.** blocking nav bar to minimize when scrolling up.

Do you have any idea if this is possible?
Any help in this direction will be really appreciated!
Thanks

**Comment by tungfam** [comment]
@AndreiBoariu hi, thanks a lot for the comment :)

1. I was quickly trying to do something similar to AppStore but it didn't work. Theoretically, we somehow need to add the imageView to the same view as a large title (from what I understand how Apple did it). And then it will hide the same way the large title is hidden. But for this short of time trying I wasn't able to do it.

2. Good idea. I was able to do it this way:
- go to method `moveAndResizeImageForPortrait`
- line 153 (after doing `imageView.transform`)
- add this code:

```swift
        let imageViewCurrentSize = imageView.frame.width
        let currentDiffSize = Const.ImageSizeForLargeState - imageViewCurrentSize
        let maxDiff = Const.ImageSizeForLargeState - Const.ImageSizeForSmallState
        let alpha = (maxDiff - currentDiffSize) / maxDiff
        imageView.alpha = alpha
```

Here is the video of how it works:
![2019-11-03 10 59 24](https://user-images.githubusercontent.com/17186720/68083472-18851580-fe29-11e9-8849-30b2f2f92b86.gif)


Additional note:
I feel like the alpha needs to be changed a bit faster. Play around with it depending on your requirements:)

Hope it helps, please let me know if not.

**Comment by tungfam** [comment]
@AndreiBoariu btw the solution 3 that you mentioned is very easy to do (if I understood you right). 

1. Simply **do not** use the large title (set `prefersLargeTitles = false`)
2. Add a static UIView under the navigation bar and set it up the way you need.
3. Put table view **under** this UIView and it will scroll without hiding this UIView.

Additionally: btw, maybe also look into Section Header View of the Table View. I have a feeling that also can work for you. If you have 1 section only then it will stick at the very top. Don't forget to set tableView's style to `.plain`

**Comment by AndreiBoariu** [comment]
@tungfam Thanks man for your help. Going to implement, and I will let you know.

**Comment by AndreiBoariu** [comment]
@tungfam It worked brilliant, but still I have to update a little more because in case of adding search bar, the image is over it because of `imgvUserProfile.bottomAnchor`. Any idea if we can get the big label reference and center the image to it ?

I tried `.topAnchor` but no success.

Totally appreciate your help!

**Comment by tungfam** [comment]
@AndreiBoariu sorry I'm not sure I know what is `imgvUserProfile`.

>Any idea if we can get the big label reference and center the image to it ?

No, I don't. But you can try to go through all subviews and find a UILabel type of object.

Also, I'm not sure I understand what do you want to achieve. Maybe try to explain or share images.

**Comment by AndreiBoariu** [comment]
@tungfam `imgvUserProfile` is the image you used in your eg: `imageView`. I just renamed it in my code.
![Here is a gif](https://media.giphy.com/media/ZZTqW0I9Tyed8MjnXo/giphy.gif)

So, let me explain again.
`tabBarController?.navigationItem.searchController = UISearchController(searchResultsController: nil)` adding this line on my code, it will add search bar under the navigation bar. Currently the `imageView` bottom constraint is set to `navigationBar` bottom with some padding. 

In my case, to keep the `imageView` on the same line with big title label, I have to set constraints relative to this one, thats why I asked about this label reference.

Thanks

**Comment by AndreiBoariu** [comment]
I tried this solution by accessing `navigationBar.subviews` and seems it works ok.
```
imgvUserProfile!.translatesAutoresizingMaskIntoConstraints = false
NSLayoutConstraint.activate([
	imgvUserProfile!.rightAnchor.constraint(equalTo: navigationBar.rightAnchor,
									 constant: -Constants.ImageRightMargin),
	imgvUserProfile!.heightAnchor.constraint(equalToConstant: Constants.ImageSizeForLargeState),
	imgvUserProfile!.widthAnchor.constraint(equalTo: imgvUserProfile!.heightAnchor)
	])
		
for parent in navigationBar.subviews {
	for view in parent.subviews {
		if view is UILabel {
			imgvUserProfile!.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: 0).isActive = true
			break
		}
	}
}
```

**Comment by tungfam** [comment]
@AndreiBoariu sorry for the late reply.

If it works, it's good.

Alternatively, since the bottom anchor of the resizing image is dynamic, you can adjust the code the way so that it will not move too much down, and stay on the same level as the label.

**Comment by tungfam** [comment]
@AndreiBoariu I'll close the issue. In case you have other questions please re-open :)
