### ISSUE TITLE
Set image on the left side

### ISSUE THREAD

**Issue by tungfam** [tungfam/ImageInNavigationBarDemo#9]

**Comment by Rushang007** [comment]
Hey I want to like this, i had tried but the problem in navigation position 
![Screenshot 2019-11-09 at 2 41 03 PM](https://user-images.githubusercontent.com/16713953/68526221-889b0c00-02ff-11ea-8364-a9d5b6b966bd.png)

**Comment by tungfam** [comment]
@Rushang007 which app is it? can you please send a link so I can have a look on how it works there.

**Comment by Rushang007** [comment]
It's not an app, its just wireframe design

**Comment by tungfam** [comment]
From what I see it's an android design. They have different patterns.

But anyway, if you have such a task to do this design.

1. Try to access the label and set an offset. I'm not sure if there are official api for that but you can try to find.
2. Put spaces in the title (very bad solution).
3. Create a custom navigation bar.

**Comment by Rushang007** [comment]
@tungfam I know its bad way while I searching about that I found your code So i think you know that how to use the left side. 

BTW Thanks.

**Comment by tungfam** [comment]
The thing is that my solution is already like a hack because Apple doesn't provide APIs to do it properly.

So the more we "change" the defaul iOS patterns the "hackier" solution comes into play.

So I would suggest either to discuss with designer to make it easier so that you can use Apple's proper design solutions, or create your own custom nav bar.
